#! /bin/bash

##############################################################################
# FILE: (bash script) localpython
# AUTHOR: R-Logik, Deutschland. https://github.com/RLogik/phpytex
# CREATED: 28.07.2020
# DESCRIPTION:
#   script to use the locally install venv version of python
# NOTES:
#
#     Installation:
#     ~~~~~~~~~~~~~
#     1. modify the first 2 lines of this script if necessary.
#     2. you may need to run
#            dos2unix <name of this script>
#        beforehand. Then run
#            [sudo] chmod +x <name of this script>
#        in bash, to be able to use this script.
#
#     Usage:
#     ~~~~~~~~~~~~~
#
#       ./localpython [ARGUMENTS]
#
#    where the arguments are just as you would use them
#    for the python/python3 command
#
##############################################################################

python_path="env/bin/python3";
$python_path "$@";
