#!/usr/bin/env bash

##############################################################################
# DESCRIPTION:
# Script to automate installation + management of Phpytex programme versions
##############################################################################

##############################################################################
# GLOBAL VARIABLES + CONSTANTS
##############################################################################

SCRIPTARGS="$@";
FLAGS=( "$@" );
OUT="/dev/stdout";
ERR="/dev/stderr";
VERBOSE="/dev/null";
LOCALDIST=".phpytex";
APPNAME="phpytex";

##############################################################################
# METHODS: Messages
##############################################################################

# Show help
function show_help() {
    echo -e "" >> $OUT;
    echo -e "Usage guide for \033[92;1mphpytex\033[0m installer"; >> $OUT
    echo -e "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"; >> $OUT
    echo -e "" >> $OUT;
    echo -e "    \033[1minstallphpytex\033[0m \033[2mflags\033[0m \033[1mTAG\033[0m" >> $OUT;
    echo -e "" >> $OUT;
    echo -e "  Required Arguments:" >> $OUT;
    echo -e "    \033[93mTAG\033[0m        \033[2mTag name of distribution (cf. https://github.com/RLogik/phpytex/releases).\033[0m" >> $OUT;
    echo -e "" >> $OUT;
    echo -e "  Flag options:" >> $OUT;
    echo -e "    \033[93m--help\033[0m     \033[2mDisplays this help information.\033[0m"                           >> $OUT;
    echo -e "    \033[93m--git\033[0m      \033[2mInstall from git artefacts, docker artefacts.\033[0m"             >> $OUT;
    echo -e "               \033[2mIf unused, attempts to link to local distribution.\033[0m";                      >> $OUT;
    # echo -e "    \033[93m--no-venv\033[0m  \033[2mIf used, python packages may be installed to your system.\033[0m" >> $OUT;
    # echo -e "               \033[2m(Not recommended. By default a virtual environment is used.)\033[0m";            >> $OUT;
    echo -e "    \033[93m--force\033[0m    \033[2mForces reinstall (depends if version already installed).\033[0m"  >> $OUT;
    echo -e "" >> $OUT;
    echo -e "" >> $OUT;
    echo -e "  NOTES:" >> $OUT;
    echo -e "    1. The installation process involves installing python packages to your current environment."             >> $OUT;
    echo -e "    2. Ensure to add \033[1m${HOME}/${LOCALDIST}/bin\033[0m to your PATH variable."                           >> $OUT;
    echo -e "       To permanently set this add the line"                                                                  >> $OUT;
    echo -e "" >> $OUT;
    echo -e "         \033[94mexport PATH=\"\$HOME/${LOCALDIST}/bin:\$PATH\";\033[0m"                                      >> $OUT
    echo -e "" >> $OUT;
    echo -e "       to \033[1m${HOME}/.bash_profile\033[0m or call"                                                        >> $OUT;
    echo -e "" >> $OUT;
    echo -e "         \033[94mecho \"export PATH=\\\"\$HOME/${LOCALDIST}/bin:\$PATH\\\";\" >> \$HOME/.bash_profile\033[0m" >> $OUT;
    echo -e "" >> $OUT;
}

function show_distributions() {
    local dist=( $( ls $HOME/$LOCALDIST/. | grep -E "(^|^v)[[:digit:]]" ) );
    local numdist=${#dist[@]};
    if [ $numdist -gt 0 ]; then
        echo -e "[\033[94;1mINFO\033[0m] Local distribution \033[1m${HOME}/${LOCALDIST}\033[0m currently contains the following version/s of \033[92;1mphpytex\033[0m:" >> $OUT;
        local tag;
        for tag in ${dist[@]}; do
            echo -e "       - ${tag}";
        done
        echo -e "[\033[94;1mINFO\033[0m] Call \033[92minstallphpytex \033[1mTAG\033[0m to link locally installed versions to the \033[92;1mphpytex\033[0m command."         >> $OUT;
    else
        echo -e "[\033[94;1mINFO\033[0m] Local distribution \033[1m${HOME}/${LOCALDIST}\033[0m currently contains no version/s of \033[92;1mphpytex\033[0m." >> $OUT;
        echo -e "[\033[94;1mINFO\033[0m] Call \033[92minstallphpytex --git \033[1mTAG\033[0m to install a version of \033[92;1mphpytex\033[0m locally." >> $OUT;
    fi
}

##############################################################################
# MAIN METHODS
##############################################################################

# Creates a local copy of versions of phpytex
function create_local_copy() {
    local force=$1;
    local use_venv=$2;
    local path="$3";
    local tag="$4";
    local homepath="$HOME/$LOCALDIST/$tag";

    ! [ -d "$HOME" ] && echo -e "[\033[91;1mERROR\033[0m] Could not access the home directory <\033[1m${HOME}\033[0m>." >> $ERR && return 1;
    require_folder "$HOME/$LOCALDIST" || return 1;

    # determine whether to overwrite existing installation:
    if [ -d "$HOME/$LOCALDIST/$tag" ]; then
        if ( $force ); then
            rm -rf "$HOME/$LOCALDIST/$tag";
        else
            cli_ask_expect "Do you wish to overwrite existing installation of \033[92;1mphpytex\033[0m:\033[1m${tag}\033[0m in \033[1m${homepath}\033[0m? (y/n) " \
                "^(y|n)$";
            [ "$answer" == "y" ] && rm -rf "$HOME/$LOCALDIST/$tag";
        fi
    fi
    # if non-existent / to be overwritten, install distribution:
    if ! [ -d "$HOME/$LOCALDIST/$tag" ]; then
        build_phpytex_binary $use_venv "$path" || return 1;
        require_folder "$HOME/$LOCALDIST/$tag" || return 1;
        cp -r "${path}/dist/."          "$HOME/$LOCALDIST/$tag/dist";
        cp    "${path}/.env"            "$HOME/$LOCALDIST/$tag/.env";
        cp    "${path}/README.md"       "$HOME/$LOCALDIST/$tag/README.md";
    fi
    return 0;
}

function build_phpytex_binary() {
    local use_venv=$1;
    local path="$2";

    # see README.md in respository for details of installation:
    echo -e "[\033[94;1mINFO\033[0m] Build binary from distribution.";
    pushd $path >> $VERBOSE;
        chmod +x scripts/*.sh;
        # ./scripts/build.sh --venv $use_venv --mode setup;
        ./scripts/build.sh --venv false --mode setup; # force usage of system python!
        ./scripts/build.sh --mode dist;
    popd >> $VERBOSE;
    ! [ -f "$path/dist/phpytex" ] && echo -e "[\033[91;1mERROR\033[0m] Generation of binary failed." >> $ERR && return 1;

    echo -e "[\033[94;1mINFO\033[0m] Generation successful." >> $OUT;
    return 0;
}

# Obtain artefact from local source
function link_command_to_distribution() {
    local tag="$1";
    local path="$HOME/$LOCALDIST/$tag";
    local folder="$HOME/$LOCALDIST/bin";

    ! [ -d "$path" ] && echo -e "[\033[91;1mERROR\033[0m] Invalid value for \033[1mTAG\033[0m." >> $ERR && return 1;
    [ -d "$folder" ] && rm -rf "$folder";
    require_folder "$folder" || return 1;
    cp "${path}/dist/${APPNAME}" "$HOME/$LOCALDIST/bin";
    echo -e "[\033[94;1mINFO\033[0m] Linked \033[1mphpytex\033[0m command to \033[1m${path}/dist/phpytex\033[0m:";
    return 0;
}

# Obtain artefact from Git repository
function get_artefact_from_repo() {
    local url_info="https://github.com/RLogik/phpytex/releases";
    !( check_curl && check_tar ) && echo -e "You need \033[1mcurl\033[0m and \033[1mtar\033[0m in order to be able to use this command." >> $ERR && exit 1;
    local force=$1;
    local use_venv=$2;
    local tag="$3";
    local file="phpytex.tar.gz";
    local url="https://github.com/RLogik/phpytex/archive/refs/tags";         # scheme: {url}/{tag}.tar.gz
    # local url="https://codeload.github.com/RLogik/phpytex/tar.gz/refs/tags"; # scheme: {url}/{tag}
    local success=1;
    local dest_temp="$( set_temporary_folder )";

    # Download zip archive from repository:
    echo -e "[\033[94;1mINFO\033[0m] Download artefact from git repository.";
    local urls=( "${url}/${tag}.tar.gz" "${url}/v${tag}.tar.gz" );
    local url_;
    for url_ in "${urls[@]}"; do
        curl -L "${url_}" -o "${dest_temp}/${file}" 2> $VERBOSE >> $VERBOSE \
            && tar -xzf "${dest_temp}/${file}" --directory "${dest_temp}" 2> $VERBOSE >> $VERBOSE \
            && success=0 && break;
    done
    [ $success -eq 1 ] && echo -e "Tagname \033[1m${tag}\033[0m could not be found! Please refer to \033[94;1m${url_info}\033[0m for valid tag names." >> $ERR && rm -rf "${dest_temp}";

    # extract file name
    local path="$( ls -d ${dest_temp}/*/ 2> $VERBOSE | head -1 | sed -E "s/\/$//" )";
    [ $success -eq 0 ] && create_local_copy $force $use_venv "${path}" "${tag}" || success=1;
    [ $success -eq 0 ] && link_command_to_distribution "${tag}" || success=1;

    # Cleanup
    rm -rf "${dest_temp}";
    return $success;
}

##############################################################################
# AUXILIARY METHODS: cli
##############################################################################

function has_arg() {
    echo "$1" | grep -Eq "(^.*[[:space:]]|^)$2([[:space:]].*$|$)";
}

function cli_ask_expect() {
    msg="$1";
    patternanswer="$2";
    answer="";
    while ( true ); do
        echo -ne "$msg" >> $OUT && read answer;
        ( echo "$answer" | grep -Eq "$patternanswer" ) && break;
    done
}

##############################################################################
# AUXILIARY METHODS: system requirements
##############################################################################

function check_curl() { ( curl --version >> $VERBOSE 2> $VERBOSE ) && return 0 || return 1; }
function check_tar() { ( tar --version >> $VERBOSE 2> $VERBOSE ) && return 0 || return 1; }

##############################################################################
# AUXILIARY METHODS: Folders
##############################################################################

function require_folder() {
    local folder="$1";
    ! [ -d "$folder" ] && mkdir "$folder";
    ! [ -d "$folder" ] && echo -e "[\033[91;1mERROR\033[0m] Could not find or create <\033[1m${folder}\033[0m>." >> $ERR && return 1;
    return 0;
}

# Create temporary folder
function set_temporary_folder() {
    local name="tmp";
    local path;
    local k=0;
    while [[ -d "${name}_${k}" ]] || [[ -f "${name}_${k}" ]]; do k=$(( $k + 1 )); done;
    path="${name}_${k}";
    mkdir "$path" && echo "${path}";
}

##############################################################################
# PROCESS CLI ARGS
##############################################################################

TAG=""; [[ ${#FLAGS} -gt 0 ]] && TAG="${FLAGS[-1]}";
( echo "$TAG" | grep -Eq "^-+" ) && TAG="";
TAG="$( echo "$TAG" | sed -E "s/^v([[:digit:]]+.*)$/\1/gi" )";
flag_git=false;       ( has_arg "$SCRIPTARGS" "-+(git|github)" ) && flag_git=true;
flag_force=false;     ( has_arg "$SCRIPTARGS" "-+(f|force)" )    && flag_force=true;
flag_venv=true;       ( has_arg "$SCRIPTARGS" "-+no-venv" )      && flag_venv=false;
SUCCESS=0;

if ( has_arg "$SCRIPTARGS" "-+(help|man|info)" ); then
    show_help;
    exit 0;
elif [ "$TAG" == "" ]; then
    echo -e "" >> $ERR;
    echo -e "[\033[91mERROR\033[0m] \033[1m{TAG}\033[0m argument cannot be empty!" >> $ERR;
    show_help;
    exit 1;
elif ( $flag_git ); then
    get_artefact_from_repo $flag_force $flag_venv "${TAG}";
    SUCCESS=$?;
else
    link_command_to_distribution "${TAG}" && exit 0;
    SUCCESS=1;
fi

show_distributions;
exit $SUCCESS;
