#!/usr/bin/env bash

##############################################################################
# DESCRIPTION:
# Script to automate installation + management of Phpytex programme versions
##############################################################################

##############################################################################
# GLOBAL VARIABLES + CONSTANTS
##############################################################################

SCRIPTARGS="$@";
FLAGS=( "$@" );
ERR="/dev/stderr";
VERBOSE="/dev/null";
LOCALDIST=".phpytex";
APPNAME="phpytex";

##############################################################################
# METHODS: Messages
##############################################################################

# Show help
function show_help() {
    echo -e "";
    echo -e "Usage guide for \x1b[92;1mphpytex\x1b[0m installer";
    echo -e "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~";
    echo -e "";
    echo -e "    \x1b[1minstallphpytex\x1b[0m \x1b[2mflags\x1b[0m \x1b[1mTAG\x1b[0m";
    echo -e "";
    echo -e "  Required Arguments:";
    echo -e "    \x1b[93mTAG\x1b[0m        \x1b[2mTag name of distribution (cf. https://github.com/RLogik/phpytex/releases).\x1b[0m";
    echo -e "";
    echo -e "  Flag options:";
    echo -e "    \x1b[93m--help\x1b[0m     \x1b[2mDisplays this help information.\x1b[0m";
    echo -e "    \x1b[93m--git\x1b[0m      \x1b[2mInstall from git artefacts, docker artefacts.\x1b[0m";
    echo -e "               \x1b[2mIf unused, attempts to link to local distribution.\x1b[0m";
    echo -e "    \x1b[93m--force\x1b[0m    \x1b[2mForces reinstall (depends if version already installed).\x1b[0m";
    echo -e "";
    echo -e "";
    echo -e "  NOTES:";
    echo -e "    1. The installation process involves installing python packages to your current environment.";
    echo -e "    2. Ensure to add \x1b[1m\$HOME/${LOCALDIST}/bin\x1b[0m to your PATH variable.";
    echo -e "       To permanently set this add the line";
    echo -e "";
    echo -e "         \x1b[94mexport PATH=\"\$HOME/${LOCALDIST}/bin:\$PATH\";\x1b[0m";
    echo -e "";
    echo -e "       to \x1b[1m${HOME}/.bash_profile\x1b[0m or call";
    echo -e "";
    echo -e "         \x1b[94mecho \"export PATH=\\\"\$HOME/${LOCALDIST}/bin:\$PATH\\\";\" >> \$HOME/.bash_profile\x1b[0m";
    echo -e "";
}

function show_distributions() {
    local dist=( $( ls $HOME/$LOCALDIST/. | grep -E "(^|^v)[[:digit:]]" ) );
    local numdist=${#dist[@]};
    if [ $numdist -gt 0 ]; then
        echo -e "[\x1b[94;1mINFO\x1b[0m] Local distribution \x1b[1m${HOME}/${LOCALDIST}\x1b[0m currently contains the following version/s of \x1b[92;1mphpytex\x1b[0m:";
        local tag;
        for tag in ${dist[@]}; do
            echo -e "       - ${tag}";
        done
        echo -e "[\x1b[94;1mINFO\x1b[0m] Call \x1b[92minstallphpytex \x1b[1mTAG\x1b[0m to link locally installed versions to the \x1b[92;1mphpytex\x1b[0m command.";
    else
        echo -e "[\x1b[94;1mINFO\x1b[0m] Local distribution \x1b[1m${HOME}/${LOCALDIST}\x1b[0m currently contains no version/s of \x1b[92;1mphpytex\x1b[0m.";
        echo -e "[\x1b[94;1mINFO\x1b[0m] Call \x1b[92minstallphpytex --git \x1b[1mTAG\x1b[0m to install a version of \x1b[92;1mphpytex\x1b[0m locally.";
    fi
}

##############################################################################
# MAIN METHODS
##############################################################################

# Creates a local copy of versions of phpytex
function create_local_copy() {
    local force=$1;
    local use_venv=$2;
    local path="$3";
    local tag="$4";
    local homepath="$HOME/$LOCALDIST/$tag";

    ! [ -d "$HOME" ] && echo -e "[\x1b[91;1mERROR\x1b[0m] Could not access the home directory <\x1b[1m${HOME}\x1b[0m>." >> $ERR && return 1;
    require_folder "$HOME/$LOCALDIST" || return 1;

    # determine whether to overwrite existing installation:
    if [ -d "$HOME/$LOCALDIST/$tag" ]; then
        if ( $force ); then
            rm -rf "$HOME/$LOCALDIST/$tag";
        else
            cli_ask_expect "Do you wish to overwrite existing installation of \x1b[92;1mphpytex\x1b[0m:\x1b[1m${tag}\x1b[0m in \x1b[1m${homepath}\x1b[0m? (y/n) " \
                "^(y|n)$";
            [ "$answer" == "y" ] && rm -rf "$HOME/$LOCALDIST/$tag";
        fi
    fi
    # if non-existent / to be overwritten, install distribution:
    if ! [ -d "$HOME/$LOCALDIST/$tag" ]; then
        build_phpytex_binary $use_venv "$path" || return 1;
        require_folder "$HOME/$LOCALDIST/$tag" || return 1;
        cp -r "${path}/dist/."          "$HOME/$LOCALDIST/$tag/dist";
        cp    "${path}/.env"            "$HOME/$LOCALDIST/$tag/.env";
        cp    "${path}/README.md"       "$HOME/$LOCALDIST/$tag/README.md";
    fi
    return 0;
}

function build_phpytex_binary() {
    local use_venv=$1;
    local path="$2";

    # see README.md in respository for details of installation:
    echo -e "[\x1b[94;1mINFO\x1b[0m] Build binary from distribution.";
    pushd $path >> $VERBOSE;
        make --always-make setup; # force usage of system python!
        make --always-make build;
    popd >> $VERBOSE;
    ! [ -f "$path/dist/phpytex" ] && echo -e "[\x1b[91;1mERROR\x1b[0m] Generation of binary failed." >> $ERR && return 1;

    echo -e "[\x1b[94;1mINFO\x1b[0m] Generation successful.";
    return 0;
}

# Obtain artefact from local source
function link_command_to_distribution() {
    local tag="$1";
    local path="$HOME/$LOCALDIST/$tag";
    local folder="$HOME/$LOCALDIST/bin";

    ! [ -d "$path" ] && echo -e "[\x1b[91;1mERROR\x1b[0m] Invalid value for \x1b[1mTAG\x1b[0m." >> $ERR && return 1;
    [ -d "$folder" ] && rm -rf "$folder";
    require_folder "$folder" || return 1;
    cp "${path}/dist/${APPNAME}" "$HOME/$LOCALDIST/bin";
    echo -e "[\x1b[94;1mINFO\x1b[0m] Linked \x1b[1mphpytex\x1b[0m command to \x1b[1m${path}/dist/phpytex\x1b[0m:";
    return 0;
}

# Obtain artefact from Git repository
function get_artefact_from_repo() {
    local url_info="https://github.com/RLogik/phpytex/releases";
    !( check_curl && check_tar ) && echo -e "You need \x1b[1mcurl\x1b[0m and \x1b[1mtar\x1b[0m in order to be able to use this command." >> $ERR && exit 1;
    local force=$1;
    local use_venv=$2;
    local tag="$3";
    local file="phpytex.tar.gz";
    local url="https://github.com/RLogik/phpytex/archive/refs/tags";         # scheme: {url}/{tag}.tar.gz
    # local url="https://codeload.github.com/RLogik/phpytex/tar.gz/refs/tags"; # scheme: {url}/{tag}
    local success=1;
    local dest_temp="$( set_temporary_folder )";

    # Download zip archive from repository:
    echo -e "[\x1b[94;1mINFO\x1b[0m] Download artefact from git repository.";
    local urls=( "${url}/${tag}.tar.gz" "${url}/v${tag}.tar.gz" );
    local url_;
    for url_ in "${urls[@]}"; do
        curl -L --proto '=https' --tlsv1.3 "${url_}" -o "${dest_temp}/${file}" \
        && tar -xzf "${dest_temp}/${file}" --directory "${dest_temp}" \
        && success=0 \
        && break;
    done
    [ $success -eq 1 ] && echo -e "Tagname \x1b[1m${tag}\x1b[0m could not be found! Please refer to \x1b[94;1m${url_info}\x1b[0m for valid tag names." >> $ERR && rm -rf "${dest_temp}";

    # extract file name
    local path="$( ls -d ${dest_temp}/*/ 2> $VERBOSE | head -1 | sed -E "s/\/$//" )";
    [ $success -eq 0 ] && create_local_copy $force $use_venv "${path}" "${tag}" || success=1;
    [ $success -eq 0 ] && link_command_to_distribution "${tag}" || success=1;

    # Cleanup
    rm -rf "${dest_temp}";
    return $success;
}

##############################################################################
# AUXILIARY METHODS: cli
##############################################################################

function has_arg() {
    echo "$1" | grep -Eq "(^.*[[:space:]]|^)$2([[:space:]].*$|$)";
}

function cli_ask_expect() {
    msg="$1";
    patternanswer="$2";
    answer="";
    while ( true ); do
        echo -ne "$msg" && read answer;
        ( echo "$answer" | grep -Eq "$patternanswer" ) && break;
    done
}

##############################################################################
# AUXILIARY METHODS: system requirements
##############################################################################

function check_curl() { ( curl --version >> $VERBOSE 2> $VERBOSE ) && return 0 || return 1; }
function check_tar() { ( tar --version >> $VERBOSE 2> $VERBOSE ) && return 0 || return 1; }

##############################################################################
# AUXILIARY METHODS: Folders
##############################################################################

function require_folder() {
    local folder="$1";
    ! [ -d "$folder" ] && mkdir "$folder";
    ! [ -d "$folder" ] && echo -e "[\x1b[91;1mERROR\x1b[0m] Could not find or create <\x1b[1m${folder}\x1b[0m>." >> $ERR && return 1;
    return 0;
}

# Create temporary folder
function set_temporary_folder() {
    local name="tmp";
    local path;
    path="$( mktemp -d -t "${name}_XXXXX" )";
    echo "${path}";
}

##############################################################################
# PROCESS CLI ARGS
##############################################################################

TAG=""; [[ ${#FLAGS} -gt 0 ]] && TAG="${FLAGS[-1]}";
( echo "$TAG" | grep -Eq "^-+" ) && TAG="";
TAG="$( echo "$TAG" | sed -E "s/^v([[:digit:]]+.*)$/\1/gi" )";
flag_git=false;       ( has_arg "$SCRIPTARGS" "-+(git|github)" ) && flag_git=true;
flag_force=false;     ( has_arg "$SCRIPTARGS" "-+(f|force)" )    && flag_force=true;
flag_venv=true;       ( has_arg "$SCRIPTARGS" "-+no-venv" )      && flag_venv=false;
SUCCESS=0;

if ( has_arg "$SCRIPTARGS" "-+(help|man|info)" ); then
    show_help;
    exit 0;
elif [ "$TAG" == "" ]; then
    echo -e "" >> $ERR;
    echo -e "[\x1b[91mERROR\x1b[0m] \x1b[1m{TAG}\x1b[0m argument cannot be empty!" >> $ERR;
    show_help;
    exit 1;
elif ( $flag_git ); then
    get_artefact_from_repo $flag_force $flag_venv "${TAG}";
    SUCCESS=$?;
else
    link_command_to_distribution "${TAG}" && exit 0;
    SUCCESS=1;
fi

show_distributions;
exit $SUCCESS;
