#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations;
import sys;
import os;
import re;
import random;
import subprocess;

################################
# USER IMPORTS

{imports}

# END OF USER IMPORTS
################################

____phpytex_params____ = dict(
    lines = dict(
        post_compile = [ ],
        anon         = [ ],
        bib          = dict(),
    ),
    rootdir        = '{root}',
    path           = '{path}',
    fname          = '{fname}',
    insert_bib     = {insert_bib},
    seed           = {seed},
    ctr_emptylines = 0,
    length         = 0,
    length_max     = {length_max},
    length_error   = False,
);
__FNAME__  = '<undefined>';
__ROOT__   = '.';
__DIR__    = '.';
__IGNORE__ = False;

## reseed-funktion:
def ____reseed():
    global ____phpytex_params____;
    random.seed(____phpytex_params____['seed']);
    return True;

## record + print-to-latex
def ____cleardocument():
    with open(____phpytex_params____['path'], 'w') as fp:
        fp.write('');
    return;

def ____forceprint(s: str, anon=False):
    global ____phpytex_params____;
    fp = ____phpytex_params____['filetex'];

    n = len(____phpytex_params____['lines']['post_compile']);
    with open(____phpytex_params____['path'], 'a') as fp:
        for _s in re.split(r'\r?\n', s):
            print(_s, file=fp);
            ____phpytex_params____['lines']['post_compile'].append(_s);
            if anon:
                ____phpytex_params____['lines']['anon'].append(n);
            n += 1;
    pass;

def ____print(s: str, anon=False):
    global ____phpytex_params____;
    global __IGNORE__;

    if __IGNORE__:
        return;
    if ____phpytex_params____['length_error']:
        return;

    ## reduces blocks of empty lines to single empty lines:
    ____phpytex_params____['ctr_emptylines'] = (____phpytex_params____['ctr_emptylines'] + 1) if re.match(r'^\s*$', s) else 0;
    if ____phpytex_params____['ctr_emptylines'] > 1:
        return;

    ____phpytex_params____['length'] += 1;
    ____phpytex_params____['length_error'] = ____phpytex_params____['length_error'] or ( ____phpytex_params____['length'] > ____phpytex_params____['length_max'] );
    ____forceprint(s, anon=anon);
    pass;

def ____insertbib(
    fname:  str,
    src:    str,
    anon:   bool = False
):
    global ____phpytex_params____;

    line = '\\bibliography{{{{\'{{file}}\'}}}}'.format(file=os.path.splitext(fname)[0]);
    with open(____phpytex_params____['path'], 'a') as fp:
        print(line, file=fp);
    # read file and insert contents:
    n = len(____phpytex_params____['lines']['post_compile']);
    ____phpytex_params____['lines']['post_compile'].append(line);
    if not ( src in ____phpytex_params____['lines']['bib'] ):
        ____phpytex_params____['lines']['bib'][src] = [];
    if anon:
        ____phpytex_params____['lines']['anon'].append(n);
    elif ____phpytex_params____['insert_bib']:
        ____phpytex_params____['lines']['bib'][src].append(n);
    pass;
