openapi: 3.0.3
info:
  version: x.y.z
  title: Schemata for CLI arguments
  description: |-
    Schemata for CLI arguments internal configuration.
servers:
  - url: "."
paths: {}
components:
  schemas:
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Arguments
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ProgrammeArguments:
      description: |-
        Structure of CLI arguments.
      type: object
      properties:
        mode:
          $ref: "#/components/schemas/EnumProgrammeMode"
          # will be overwritten by enum default
          default: null
        quiet:
          type: boolean
          default: false
        debug:
          type: boolean
          default: false
        plain:
          type: boolean
          default: false
        file:
          type: string
        # for 'on-the-fly' alterations:
        parameters-options:
          type: string
        transpile-options:
          type: string
        stamp-options:
          type: string
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # ENUM Mode
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    EnumProgrammeMode:
      description: |-
        An enumeration of possible options for mode
      type: string
      enum:
        - 'version'
        - 'help'
        - 'run'
        - 'template'
        - 'example'
      default: 'help'
