openapi: 3.0.3
info:
  version: x.y.z
  title: Schemata for app config
  description: |-
    Schemata for app internal configuration.
servers:
  - url: "."
paths: {}
definitions:
    FileString: &file_string
      description: Data type for a string to be the base name of a file.
      type: string
      pattern: '^[^\\\/]*(\.[^\\\/]+)?$'
    PathToFileString: &path_to_file_string
      description: Data type for a string to be a path to a file.
      type: string
      pattern: '^[^\\\/]+([\\\/][^\\\/]+)*(\.[^\\\/]+)?$'
    PathToDirString: &path_to_dir_string
      description: Data type for a string to be a path to a directory.
      type: string
      pattern: '^[^\\\/]+([\\\/][^\\\/]+)*$'
    PythonImportString: &python_import_string
      description: Data type for a string to constitute an import 'path' in python.
      type: string
      pattern: '^[\w\_]+(\.[\w\_]+)*$'
components:
  schemas:
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Config
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ProgrammeConfig:
      description: |-
        Internal application configuration
      type: object
      required:
        - namespace
        - assets
        - paths
        - transpile
      properties:
        namespace:
          description: Internal naming parts of transpiled python code.
          $ref: "#/components/schemas/NameSpacePython"
        assets:
          description: Paths to assets.
          $ref: "#/components/schemas/AssetsPaths"
        paths:
          description: Settings for paths and files for the transpilation process.
          $ref: "#/components/schemas/PathSettings"
        transpile:
          description: Options for transpilation.
          $ref: "#/components/schemas/TranspileOptions"
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Asset paths
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    AssetsPaths:
      description: |-
        Options pertaining purely to assets.
      type: object
      required:
        - version
        - grammar
        - template_config
        - template_example
        - template_pre
        - template_post
      properties:
        version:
          <<: *path_to_file_string
        grammar:
          <<: *path_to_file_string
        template_config:
          <<: *path_to_file_string
        template_example:
          <<: *path_to_file_string
        template_pre:
          <<: *path_to_file_string
        template_post:
          <<: *path_to_file_string
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Paths for process
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PathSettings:
      description: |-
        Options pertaining to files and paths.
      type: object
      required:
        - logging
        - file-config
        - pattern-config
        - file-transpiled
        - file-start
        - file-output
        - overwrite-stamp
        - overwrite-params
        - param-module-name
      properties:
        logging:
          <<: *path_to_file_string
          description: Path to file for logging (dev mode only).
        file-config:
          <<: *file_string
          description: Filename for user config.
        pattern-config:
          type: string
        file-transpiled:
          <<: *path_to_file_string
          description: File path for intermediate transpilation (python stage).
        file-start:
          <<: *path_to_file_string
          description: File path for starting point for transpilation.
        file-output:
          <<: *path_to_file_string
          description: File path for final transpilation (latex stage).
        # optional:
        file-stamp:
          <<: *path_to_file_string
        overwrite-stamp:
          type: boolean
        file-params-py:
          <<: *path_to_file_string
        import-params:
          <<: *python_import_string
          default: 'src.params'
        overwrite-params:
          type: boolean
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Transpilation options
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    TranspileOptions:
      description: |-
        Options for transpilation.
      type: object
      required:
        - compile-latex
        - show-tree
        - insert-bib
        - max-length
        - indent-character
        - indent-character-re
        - censor-symbol
        - offset-symbol
      properties:
        debug:
          type: boolean
          default: false
        compile-latex:
          type: boolean
        show-tree:
          type: boolean
        comments:
          $ref: "./common-schema.yaml/#/components/schemas/EnumCommentsOption"
          # will be overwritten by enum default
          default: null
        insert-bib:
          type: boolean
        max-length:
          description: Prevents transpiler from creating overlarge files
          type: integer
        seed:
          type: integer
        indent-character:
          type: string
        indent-character-re:
          type: string
        censor-symbol:
          type: string
        offset-symbol:
          type: string
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Namespace settings for transpiled python code
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    NameSpacePython:
      description: |-
        Internal naming parts of transpiled python code.
      type: object
      required:
        - param-module-name
      properties:
        param-module-name:
          type: string
