openapi: 3.0.3
info:
  version: x.y.z
  title: Schemata for app config
  description: |-
    Schemata for app internal configuration.
servers:
  - url: "."
paths: {}
definitions:
    FileString: &file_string
      description: Data type for a string to be the base name of a file.
      type: string
      pattern: '^[^\\\/]*\.[^\\\/]+$'
    PathToFileString: &path_to_file_string
      description: Data type for a string to be a path to a file.
      type: string
      pattern: '^[^\\\/]+([\\\/][^\\\/]+)*\.[^\\\/]+$'
    PathToDirString: &path_to_dir_string
      description: Data type for a string to be a path to a directory.
      type: string
      pattern: '^[^\\\/]+([\\\/][^\\\/]+)*$'
    PythonImportString: &python_import_string
      description: Data type for a string to constitute an import 'path' in python.
      type: string
      pattern: '^[\w\_]+(\.[\w\_]+)*$'
components:
  schemas:
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Config
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ProgrammeConfig:
      description: |-
        Internal application configuration
      type: object
      required:
        - paths
        - transpile
      properties:
        paths:
          description: Options pertaining to files and paths
          $ref: "#/components/schemas/ProgrammePaths"
        transpile:
          description: Options for transpilation
          $ref: "#/components/schemas/TranspileOptions"
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # File options
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ProgrammePaths:
      description: |-
        Options pertaining to files and paths.
      type: object
      required:
        - logging
        - file-config
        - file-transpiled
      properties:
        logging:
          <<: *path_to_file_string
          description: Path to file for logging (dev mode only).
        file-config:
          <<: *file_string
          description: Filename for user config.
        pattern-config:
          type: string
          default: '^(|.*\.)phpytex\.ya?ml$'
        file-transpiled:
          <<: *path_to_file_string
          description: File path for intermediate transpilation (python stage).
        file-start:
          <<: *path_to_file_string
          description: File path for starting point for transpilation.
          default: ''
        file-output:
          <<: *path_to_file_string
          description: File path for final transpilation (latex stage).
          default: ''
        # optional:
        file-stamp:
          <<: *path_to_file_string
        # with-file-stamp:
        #   type: boolean
        #   default: false
        file-params-py:
          <<: *path_to_file_string
        # with-file-params-py:
        #   type: boolean
        #   default: false
        import-param-py:
          <<: *python_import_string
        param-module-name:
          type: string
          default: 'MODULE_GLOBAL_PARAMS'
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Transpilation options
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    TranspileOptions:
      description: |-
        Options for transpilation.
      type: object
      properties:
        ignore:
          type: boolean
          default: false
        debug:
          type: boolean
          default: false
        compile-latex:
          type: boolean
          default: false
        show-tree:
          type: boolean
          default: true
        comments-auto:
          type: boolean
          default: true
        comments-on:
          type: boolean
          default: true
        insert-bib:
          type: boolean
          default: false
        overwrite-stamp:
          type: boolean
          default: true
        overwrite-params:
          type: boolean
          default: true
        max-length:
          description: Prevents transpiler from creating overlarge files
          type: integer
          default: 10000
        seed:
          type: integer
        indent-character:
          type: string
          default: '    '
        indent-character-re:
          type: string
          default: '    '
        censor-symbol:
          type: string
          default: '########'
        offset-symbol:
          type: string
          default: ''
