openapi: 3.0.3
info:
  version: x.y.z
  title: Schemata for user config
  description: |-
    Schemata for user configuration, i.e. a user's `.phpytex.yaml` file.
servers:
  - url: "."
paths: {}
definitions:
    FileString: &file_string
      description: Data type for a string to be the base name of a file.
      type: string
      pattern: '^[^\\\/]*\.[^\\\/]+$'
    PathToFileString: &path_to_file_string
      description: Data type for a string to be a path to a file.
      type: string
      pattern: '^[^\\\/]+([\\\/][^\\\/]+)*\.[^\\\/]+$'
    PathToDirString: &path_to_dir_string
      description: Data type for a string to be a path to a directory.
      type: string
      pattern: '^[^\\\/]+([\\\/][^\\\/]+)*$'
    PythonImportString: &python_import_string
      description: Data type for a string to constitute an import 'path' in python.
      type: string
      pattern: '^(\.\.|\.)[\w\_]+(\.[\w\_]+)*$'
components:
  schemas:
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # UserConfig
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    UserConfig:
      description: |-
        Model for all parts of the user config file.
      type: object
      properties:
        transpile:
          description: |-
            Configuration block for transpilation options.
          $ref: "#/components/schemas/UserTranspileBlock"
        # NOTE: Old - issue warning.
        compile:
          description: |-
            Configuration block for transpilation options.
          anyOf:
          - $ref: "#/components/schemas/UserTranspileBlock"
          - $ref: "#/components/schemas/UserTranspileOptions"
        stamp:
          description: |-
            Configuration block for stamp settings.
          $ref: "#/components/schemas/UserStampBlock"
        parameters:
          description: |-
            Configuration block for global parameters.
          $ref: "#/components/schemas/UserParametersBlock"
        files:
          description: |-
            List of files for project tree.
          type: array
          items:
            <<: *file_string
          default: []
        folders:
          description: |-
            Dictionary with keys as (sub)directories and values which recursively define the project tree.
          type: object
          additionalProperties:
            $ref: "#/components/schemas/DataTypeFolder"
          default: {}
      additionalProperties: true
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # User Compile block
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    UserTranspileBlock:
      description: |-
        Settings for compilation.
      type: object
      properties:
        options:
          $ref: "#/components/schemas/UserTranspileOptions"
      additionalProperties: false
    UserTranspileOptions:
      description: |-
        Options for compilation block.
      type: object
      required: []
      properties:
        root:
          <<: *path_to_file_string
          description: File path for starting point for transpilation.
          default: 'root.tex'
        output:
          <<: *path_to_file_string
          description: File path for final transpilation (latex stage).
          default: 'main.tex'
        debug:
          type: boolean
          default: false
        compile-latex:
          type: boolean
          default: false
        show-structure:
          type: boolean
          default: true
        comments:
          $ref: "./common-schema.yaml/#/components/schemas/EnumCommentsOption"
          # will be overwritten by enum default
          default: null
        insert-bib:
          type: boolean
          default: false
        max-length:
          description: Prevents transpiler from creating overlarge files
          type: integer
          default: 10000
        seed:
          type: integer
        tabs:
          type: boolean
          default: false
        spaces:
          type: integer
          default: 4
        additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # User Compile options
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    UserStampBlock:
      description: |-
        Settings for comment stamp to be placed at top of transpiled .tex file.
      type: object
      required: []
      properties:
        file:
          <<: *file_string
          default: 'stamp.tex'
        overwrite:
          type: boolean
          default: true
        options:
          type: object
          default: {}
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # User Parameters options
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    UserParametersBlock:
      description: |-
        Settings for user defined global parameters across entire document.
      type: object
      required: []
      properties:
        file:
          <<: *python_import_string
          default: src.parameters
        overwrite:
          type: boolean
          default: true
        options:
          type: object
          additionalProperties: true
          default: {}
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # DATA TYPE Folder
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    DataTypeFolder:
      description: |-
        Allow for the recursive definition of a folder structure.
      type: object
      properties:
        files:
          type: array
          items:
            <<: *file_string
          default: []
        folders:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/DataTypeFolder"
          default: {}
      additionalProperties: false
