openapi: 3.0.3
info:
  version: x.y.z
  title: Schemata for user config
  description: |-
    Schemata for user configuration, i.e. a user's `.phpytex.yaml` file.
servers:
  - url: "."
paths: {}
definitions:
    FileString: &file_string
      description: Data type for a string to be the base name of a file.
      type: string
      pattern: '^[^\\\/]*\.[^\\\/]+$'
    PathToFileString: &path_to_file_string
      description: Data type for a string to be a path to a file.
      type: string
      pattern: '^[^\\\/]+([\\\/][^\\\/]+)*\.[^\\\/]+$'
    PathToDirString: &path_to_dir_string
      description: Data type for a string to be a path to a directory.
      type: string
      pattern: '^[^\\\/]+([\\\/][^\\\/]+)*$'
    PythonImportString: &python_import_string
      description: Data type for a string to constitute an import 'path' in python.
      type: string
      pattern: '^[\w\_]+(\.[\w\_]+)*$'
components:
  schemas:
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # UserConfig
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    UserConfig:
      description: |-
        Model for all parts of the user config file.
      type: object
      properties:
        compile:
          anyOf:
          - $ref: "#/components/schemas/UserCompileBlock"
          - $ref: "#/components/schemas/UserCompileOptions"
        stamp:
          $ref: "#/components/schemas/UserStampBlock"
        parameters:
          $ref: "#/components/schemas/UserParameterBlock"
        files:
          type: array
          items:
            <<: *file_string
          default: []
        folders:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/DataTypeFolder"
          default: {}
      additionalProperties: true
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # User Compile block
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    UserCompileBlock:
      description: |-
        Settings for compilation.
      type: object
      properties:
        options:
          $ref: "#/components/schemas/UserCompileOptions"
      additionalProperties: false
    UserCompileOptions:
      description: |-
        Options for compilation block.
      type: object
      required: []
      properties:
        root:
          <<: *path_to_file_string
          description: File path for starting point for transpilation.
          default: 'root.tex'
        output:
          <<: *path_to_file_string
          description: File path for final transpilation (latex stage).
          default: 'main.tex'
        debug:
          type: boolean
          default: false
        compile-latex:
          type: boolean
          default: false
        show-structure:
          type: boolean
          default: true
        comments:
          $ref: "#/components/schemas/EnumCommentsOption"
          # will be overwritten by enum default
          default: null
        insert-bib:
          type: boolean
          default: false
        max-length:
          description: Prevents transpiler from creating overlarge files
          type: integer
        seed:
          type: integer
        tabs:
          type: boolean
          default: false
        spaces:
          type: integer
          default: 4
        additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # User Compile options
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    UserStampBlock:
      description: |-
        Settings for comment stamp to be placed at top of transpiled .tex file.
      type: object
      required: []
      properties:
        file:
          <<: *file_string
          default: 'stamp.tex'
        overwrite:
          type: boolean
          default: true
        options:
          type: object
          default: {}
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # User Parameter options
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    UserParameterBlock:
      description: |-
        Settings for user defined global parameters across entire document.
      type: object
      required: []
      properties:
        file:
          <<: *python_import_string
          default: src.parameters
        overwrite:
          type: boolean
          default: true
        options:
          type: object
          additionalProperties: true
          default: {}
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # DATA TYPE Folder
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    DataTypeFolder:
      description: |-
        Allow for the recursive definition of a folder structure.
      type: object
      properties:
        files:
          type: array
          items:
            <<: *file_string
          default: []
        folders:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/DataTypeFolder"
          default: {}
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # ENUM Comments Options
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    EnumCommentsOption:
      description: |-
        An enumeration of possible options for comments
      type: string
      enum:
        - 'auto'
        - 'on'
        - 'off'
      default: auto
