namespace:
  module-name-param: 'MODULE_GLOBAL_PARAMS'
  function-name-main: '____phpytex_main'
  function-name-file: '____phpytex_generate_file'
  function-name-pre: '____phpytex_generate_pre'
assets:
  version: 'dist/VERSION'
  grammar: 'assets/phpytex.lark'
  template-config: 'assets/template_config'
  template-example: 'assets/template_example'
  template-pre: 'assets/template_pre'
  template-post: 'assets/template_post'
paths:
  logging: 'logs/debug.log'
  file-config: '.phpytex.yaml'
  pattern-config: '^(|.*\.)phpytex\.ya?ml$'
  file-transpiled: 'transpiled_phpytex.py'
  file-start: 'root.tex'
  file-output: 'main.tex'
  overwrite-stamp: true
  overwrite-params: true
transpile:
  debug: false
  compile-latex: false
  show-tree: true
  comments: auto
  insert-bib: false
  max-length: 10000
  indent-character: '    '
  indent-character-re: '    '
  censor-symbol: '########'
  offset-symbol: ''
