# cf. https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
on:
  push:
    branches:
    - master
  # schedule:
  #   - cron:  '*/5 * * * *'
env:
  SERVER: production
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  authorise-scripts:
    runs-on: [self-hosted, linux, ubuntu-latest]
    name: Authorise the bash scripts
    steps:
    - run: "chmod +x clean.sh"
    - run: "chmod +x compile"
    - run: "chmod +x build.sh"
  clean-repo:
    runs-on: [self-hosted, linux, ubuntu-latest]
    needs: [authorise-scripts]
    name: Clean the project of any build artefacts
    steps:
    - run: "./clean.sh --force"
  compile-repo:
    name: Compile the project
    needs: [clean-repo]
    runs-on: [self-hosted, linux, ubuntu-latest]
    steps:
    - run: "./build.sh"
  release:
    name: Create release artefact
    needs: [compile-repo]
    runs-on: [self-hosted, linux, ubuntu-latest]
    steps:
    - run: ". .lib.sh  && post_build_create_release_version"
