name: CI for go project
on:
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which branch should be tested?'
        default:     'master'
        required:    true
jobs:
  ################################################################################################################################
  # Pipe for QA
  ################################################################################################################################
  pipe-qa:
    runs-on: ubuntu-20.04
    env:
      lang:     go
      app_path: dist/phpytex
    steps:
      ################################################################
      # SETUP
      ################################################################
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - name: Install system requirements via apt-get
        run: |-
          sudo apt-get install -y dos2unix
          sudo apt-get install -y apt-utils
          sudo apt-get install -y zip unzip xz-utils
          sudo apt-get clean
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Grant execution rights
        run: |-
          chmod +x scripts/*.sh
      - # only do perform this in one job
        name: Run setup
        run: |-
          ./scripts/build.sh --lang ${{ env.lang }} --mode setup
          echo "Setup for go successful"
      - name: Create binary artefact
        run: |-
          ./scripts/build.sh --lang ${{ env.lang }} --mode dist
          if ! [[ -f ${{ env.app_path }} ]]; then
            "Binary not created!"
            exit 1
          fi
          echo "Binary successfully created"
      # ################################################################
      # # BASIC CHECKS
      # ################################################################
      # - name: Check if programm works (call 'help' flag)
      #   run: |-
      #     ${{ env.app_path }} help
      # - name: Check if programm works (call 'version' flag)
      #   run: |-
      #     version="$( cat dist/VERSION )"
      #     output="$( ${{ env.app_path }} version )"
      #     if ! [[ "$output" == "$version" ]]; then
      #       echo "output=$output=/=$version"
      #       exit 1
      #     fi
      #     echo "$output"
      ################################################################
      # UNIT TESTS
      ################################################################
      - name: Run unit tests
        run: |-
          ./scripts/test.sh --lang ${{ env.lang }} --mode unit
      ################################################################
      # CASE TESTS
      ################################################################
      - name: Run case tests
        run: |-
          ./scripts/test.sh --lang ${{ env.lang }} --mode cases
