name: Create Release
on: [ push ]
jobs:
  build-python-dist:
    runs-on: ubuntu-latest
    env:
      lang:     python
      app_name: phpytex
      branch:   master
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.branch }}
    - name: Check current path
      run: pwd
    - name: Check what files exists
      run: ls
    - name: Grant execution rights
      run: chmod +x scripts/*.sh
    - name: Run setup
      run: ./scripts/build.sh --lang ${{ env.lang }} --venv false --mode setup
    - name: Check if open source code works
      run: ./scripts/build.sh --lang ${{ env.lang }} --mode run --options="version"
    - name: Check if artefact exists before creation
      run: |-
        ls dist/*;
        [ -f dist/${{ env.app_name }} ] && echo "artefact exists";
        ! [ -f dist/${{ env.app_name }} ] && echo "artefact does not exist, as expected";
    - name: Create artefact
      run: ./scripts/build.sh --lang ${{ env.lang }} --mode dist
    - name: Check if artefact exists
      run: |-
        ls dist/*;
        ! [ -f dist/${{ env.app_name }} ] && echo "artefact does not exist!" && exit 1;
        [ -f dist/${{ env.app_name }} ] && echo "artefact exists";
    - name: Check if programme works
      run: dist/${{ env.app_name }} version
