openapi: 3.0.3
info:
  version: x.y.z
  title: Schemata for app config
  description: |-
    Schemata for app internal configuration.
servers:
  - url: "."
paths: {}
components:
  schemas:
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Config
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    UserConfig:
      description: |-
        Model for all parts of the user config file.
      type: object
      properties:
        info:
          $ref: "#/components/schemas/Info"
        options:
          $ref: "#/components/schemas/AppOptions"
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Info
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Info:
      description: |-
        Contains meta data about project.
      type: object
      required:
        - title
        - description
        - author
      properties:
        title:
          type: string
        description:
          type: string
        author:
          type: string
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # App Options
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    AppOptions:
      description: |-
        Options pertaining to the rudimentary setup of the app.
      type: object
      required: []
      properties: {}