openapi: 3.0.3
info:
  version: x.y.z
  title: Schemata for user config
  description: |-
    Schemata for user configuration, i.e. a user's `.phpytex.yaml` file.
servers:
  - url: "."
paths: {}
components:
  schemas:
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # UserConfig
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    UserConfig:
      description: |-
        Model for all parts of the user config file.
      type: object
      properties:
        compile:
          $ref: "#/components/schemas/UserCompileOptions"
        stamp:
          $ref: "#/components/schemas/UserStampOptions"
        parameters:
          $ref: "#/components/schemas/UserParameterOptions"
        files:
          type: array
          items:
            type: string
            pattern: '^[^\\\/]*\.[^\\\/]+$'
          default: []
        folders:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/DataTypeFolder"
          default: {}
      additionalProperties: true
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # User Compile options
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    UserCompileOptions:
      description: |-
        Options for compilation.
      type: object
      required:
        - root
        - output
      properties:
        root:
          type: string
        output:
          type: string
        debug:
          type: boolean
          default: false
        compile-latex:
          type: boolean
          default: false
        show-structure:
          type: boolean
          default: true
        comments:
          $ref: "#/components/schemas/EnumCommentsOption"
        insert-bib:
          type: boolean
          default: false
        max-length:
          description: Prevents transpiler from creating overlarge files
          type: integer
        seed:
          type: integer
        tabs:
          type: boolean
          default: false
        spaces:
          type: integer
          default: 4
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # User Compile options
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    UserStampOptions:
      description: |-
        Options for comment stamp to be placed at top of transpiled .tex file.
      type: object
      required:
        - file
      properties:
        file:
          type: string
          pattern: '^[^\\\/]*\.[^\\\/]+$'
        overwrite:
          type: boolean
          default: true
        options:
          type: object
          default: {}
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # User Parameter options
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    UserParameterOptions:
      description: |-
        Options for comment stamp to be placed at top of transpiled .tex file.
      type: object
      required:
        - file
      properties:
        file:
          type: string
          pattern: '^[\w\_]+(\.[\w\_]+)*$'
        overwrite:
          type: boolean
          default: true
        options:
          type: object
          additionalProperties: true
          default: {}
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # DATA TYPE Folder
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    DataTypeFolder:
      description: |-
        Allow for the recursive definition of a folder structure.
      type: object
      properties:
        files:
          type: array
          items:
            type: string
            pattern: '^[^\\\/]*\.[^\\\/]+$'
          default: []
        folders:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/DataTypeFolder"
          default: {}
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # ENUM Comments Options
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    EnumCommentsOption:
      description: |-
        An enumeration of possible options for comments
      type: string
      enum:
        - 'auto'
        - 'on'
        - 'off'
      default: auto
